body: |
  # Repositories

  {groupsFormatted}

group: |
  ## {group.name}

  {repositoriesFormatted}

repository: |
  - [{repository.name}]({repository.html_url}) {repositoryLabelFormatted}  
    {repository.description}

repositoryLabel: '`{repositoryLabel}`'

groups:
- name: Stable
  topics: stable
- name: Preview
  topics: preview
