# Body format of repository list.
# Available values:
#   context: Context object passed into action as 'context' parameter.
#   groups: Array of the group objects. (Read about group object below.)
#   groupsFormatted: Formatted groups as text.
# Description of group object.
# group:
#   name: Name of group from config.
#   description: Description of group from config.
#   repositories: Array of repository objects. (Read about repository object: https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user.)
body: |
  # Repositories

  List of available repositories.

  {groupsFormatted}

# Group format of repositories.
# Available values:
#   context: Context object passed into action as 'context' parameter.
#   groups: Array of the group objects. (Same as groups in body.)
#   group: Group object. (Read about group in body description.)
#   repositoriesFormatted: Formatted repositories as text.
group: |
  ## {group.name}

  {group.description}

  {repositoriesFormatted}

# Repository format
# Available values:
#   context: Context object passed into action as 'context' parameter.
#   repositories: Array of repository objects. (Read about repository object: https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user.)
#   repository: Repository object.
#   repositoryLabelFormatted: Repository label formatted as text.
repository: |
  - [{repository.name}]({repository.html_url}) {repositoryLabelFormatted}  
    {repository.description}

# Repository label format.
# Repository label is similar label which displayed at GitHub website when repository has private, template or archived flags.
# Formatting does not applied when repository has no label, in this case empty string returned.
# Available values:
#   context: Context object passed into action as 'context' parameter.
#   repository: Repository object.
#   repositoryLabel: Repository label text.
repositoryLabel: '`{repositoryLabel}`'

# Setting to group repositories before formatting.
# Description of group settings.
# group:
#   name: Name of group.
#   description: Description of group.
#   topics: List of comma separated topic names used to determine whether to include repository in group. (Example: 'preview,legacy'.)
groups:
- name: Stable
  description: Stable repositories.
  topics: stable
- name: Preview
  description: Preview repositories.
  topics: preview
